server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frist_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.example.demo.entity